[package]
name = "untree"
version = "0.9.4"
edition = "2021"
authors = ["Alecto Irene Perez <perez.cs@pm.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = {version = "3.0.13", features = ["derive", "wrap_help"] }
